# Generated by Django 3.2 on 2021-10-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_userpackage_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.customer'),
        ),
    ]
